StringLiterals:
  EnforcedStyle: "double_quotes"

LineLength:
  Max: 80

# This offends when not tabbed way out while using case in assignment
CaseIndentation:
  Enabled: false

# Not a part of our coding conventions
Documentation:
  Enabled: false

DoubleNegation:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

DeprecatedClassMethods:
  Enabled: false

SingleLineBlockParams:
  Enabled: false

# Also just not something I've ever done or want to do...
SpaceAroundEqualsInParameterDefault:
  Enabled: false

# I don't see why... It's shorthand, just know your ruby!
SpecialGlobalVars:
  Enabled: false

# This was offending for a custom method called `collect` not on an `Enumerable`
CollectionMethods:
  Enabled: false

# Cuz we don't use any fancy characters anyway
Encoding:
  Enabled: false

# I just don't care so much about clean specs.. Like short methods and short lines
AllCops:
  Exclude:
    - spec/**
